name: Checkov Scan

on:
  pull_request:
  push:
     branches: 
        - main
jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./compliant
          framework: terraform
          external_checks_dirs: custom-policies
